### PR TITLE
Update to 1.18.2.

### PR DESCRIPTION
**Pull request by RubenNL**

### CODE REVIEW

**Comment by CAG2Mark** [comment]
Does not build, need to update ./gradle/wrapper/gradle-wrapper.properties.

I've made the change locally and will merge as soon as I've tested

**Comment by RubenNL** [comment]
Interesting. For me it worked using gradlew.

Maybe Todo for later: adding automatic tests on this repo. I can do that tomorrow or so.

**Comment by RubenNL** [comment]
we should add some script to automatically generate the death message thing.

**Comment by CAG2Mark** [comment]
I don't think that will work because extracting a natural-feeling death message from death.XXX.XXX.XXX is not trivial to do with code

**Pull request merged**
